services:
  port-broker:
    build: .
    ports:
      - "8765:8765"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV=production
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - wave-reader-network

networks:
  wave-reader-network:
    driver: bridge 